# Generated by Django 2.1.7 on 2019-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_id', models.IntegerField(max_length=8)),
                ('catalog', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='img')),
            ],
        ),
    ]
