# Generated by Django 2.1.7 on 2019-03-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoyaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('incremental', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoyaPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='boyapic',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.StudentInfo'),
        ),
        migrations.AddField(
            model_name='boyainfo',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.StudentInfo'),
        ),
    ]
